# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 00:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_api_access', models.BooleanField(default=False, help_text=b'Can this user crawl this server from their crates server?')),
                ('api_key', models.UUIDField(default=uuid.uuid4, help_text=b"Key used to identify user's crates server", unique=True)),
                ('can_upload', models.BooleanField(default=False, help_text=b'Is the user allowed to push files to this crates server? Not implemented yet.')),
                ('bytes_inbound', models.IntegerField(default=0, editable=False)),
                ('bytes_outbound', models.IntegerField(default=0, editable=False)),
                ('object_count', models.IntegerField(default=0, editable=False)),
                ('bytes_available', models.IntegerField(default=0, editable=False)),
                ('bytes_total', models.IntegerField(default=0, editable=False)),
                ('objects_common', models.IntegerField(default=0, editable=False, help_text=b'Mutual CAS objects. Good for data backup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
